Card component
Jay-Gadhiya/nebula-ui pull request #2
Opened 2022-02-01 04:31 UTC by Jay-Gadhiya

card component contains simple card, with badge, with dismiss button and shadows

2022-02-01 05:35 UTC, mohammed-sas commented
suggestion : add screenshot while raising pr, it would be easier to review

2022-02-01 05:44 UTC, mohammed-sas requested changes
suggestion : ask captain if it's okay to make card component with different html structure as your variants had different structure . 
card with shadow : there were three cards in in this variant , display one card.

2022-02-03 11:30 UTC, gadgetfather commented
![image](https://user-images.githubusercontent.com/77927918/152334637-a94296a8-9ff6-4294-a9c5-adf45d9c6232.png)
Your "add to cart" is small compared to the "add to wishlist" button. 
rest is good 👍

2022-02-03 11:30 UTC, gadgetfather approved these changes

2022-02-04 04:54 UTC, gopalbbharadva commented on components/card/card.css
> +    color: #f44336;
Suggestion: Use variables instead of hard coded color value.

2022-02-04 04:55 UTC, gopalbbharadva commented on components/card/card.css
> +    color: #fff;
Suggestion: use CSS variables.

2022-02-04 04:57 UTC, gopalbbharadva approved these changes
Your PR request should have only files related to that PR only.(E.g. if your PR is about card component then your PR should not contain any other file changes.)

2022-02-04 11:05 UTC, merged